### ISSUE TITLE
Add non-blocking dispatcher for JPA

### ISSUE THREAD

**Issue by wsargent** [playframework/play-java-jpa-example#16]
Like https://github.com/playframework/play-isolated-slick/blob/master/modules/slick/src/main/resources/application.conf#L32

**Comment by mkurz** [comment]
Also see https://github.com/playframework/playframework/issues/6489
I hope to find more time to work on https://github.com/playframework/playframework/pull/6777 as well.

**Comment by wsargent** [comment]
Fixed by https://github.com/playframework/play-java-jpa-example/pull/19
