### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by GiuseppeCiccone** [playframework/play-java-jpa-example#29]
I can't use lazy loading relations, because the method "wrap" opens a transaction that is immediately closed after that the result is returned.

The exception is 
`Caused by: java.util.concurrent.CompletionException: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role testClass.testArg, could not initialize proxy - no Session`

**Comment by wsargent** [comment]
That's not a problem with the example, though -- in DDD terms, you want an aggregate root, which is a special case of an entity.  If you need the entity to make its own calls, then it should have a link back to the repository and you can have a method on the entity that calls out and returns data through the persistence engine (i.e. it is a business object, not something returned from JPA directly).  Check out https://vaughnvernon.co/?p=838 for more details.
