### ISSUE TITLE
Project fails to boot with hibernate-core 5.2.5.Final

### ISSUE THREAD

**Issue by VeryBueno** [playframework/play-java-jpa-example#56]
I downloaded the project  from both [GitHub](https://github.com/playframework/play-java-jpa-example) and the [Examples](https://www.playframework.com/download) page. If boot it with `sbt run` or through IntelliJ, I get this error:

```
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/dom4j/io/STAXEventReader
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:44)
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.class(DefaultJPAApi.java:39)
  while locating play.db.jpa.DefaultJPAApi$JPAApiProvider
  while locating play.db.jpa.JPAApi
    for the 1st parameter of models.JPAPersonRepository.<init>(JPAPersonRepository.java:23)
  while locating models.JPAPersonRepository
  while locating models.PersonRepository
    for the 2nd parameter of controllers.PersonController.<init>(PersonController.java:28)
  while locating controllers.PersonController
    for the 2nd parameter of router.Routes.<init>(Routes.scala:30)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for the 1st parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:222)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
  at play.api.DefaultApplication.class(Application.scala:235)
  while locating play.api.DefaultApplication
  while locating play.api.Application
```

In `build.sbt`, if I upgrade `hibernate-core` from `5.2.5.Final` to `5.2.13.Final`, it works. Do you guys see this error?

**Comment by wsargent** [comment]
Sounds like https://stackoverflow.com/questions/36222306/caused-by-java-lang-classnotfoundexception-org-dom4j-io-staxeventreader.  

Should add hibernate-core to https://github.com/lightbend/templatecontrol/blob/master/src/main/resources/2.6.x.conf and auto-update it so this gets fixed upstream.

**Comment by mkurz** [comment]
`hibernate-core` was upgraded in `play-java-jpa-example` already: https://github.com/playframework/play-java-jpa-example/blob/e2df3b2d5fd25683549b2270397565fc8f17eec5/build.sbt#L14

I think we can close this now.
